"""Package-facing access to application storage and resource paths."""

from __future__ import annotations

from app_paths import (
    BASE_DIR,
    CACHE_DIR,
    CLI_LOG_PATH,
    CONFIG_DIR,
    CONFIG_PATH,
    DATABASE_PATH,
    DATA_DIR,
    DIAGNOSTICS_DIR,
    DOWNLOADS_DIR,
    EXPORTS_DIR,
    FIRST_RUN_PATH,
    GUI_LOG_PATH,
    LANGUAGE_PACKS_DIR,
    LOG_DIR,
    OFFLINE_KNOWLEDGE_DIR,
    PLUGINS_DIR,
    PROFILE_BACKUPS_DIR,
    TITLEIDS_PATH,
    StoragePaths,
    app_root,
    describe_storage,
    ensure_app_dirs,
    ensure_user_titleids_file,
    executable_root,
    portable_mode_enabled,
    resolve_storage_paths,
    resource_path,
)

__all__ = [
    "BASE_DIR",
    "CACHE_DIR",
    "CLI_LOG_PATH",
    "CONFIG_DIR",
    "CONFIG_PATH",
    "DATABASE_PATH",
    "DATA_DIR",
    "DIAGNOSTICS_DIR",
    "DOWNLOADS_DIR",
    "EXPORTS_DIR",
    "FIRST_RUN_PATH",
    "GUI_LOG_PATH",
    "LANGUAGE_PACKS_DIR",
    "LOG_DIR",
    "OFFLINE_KNOWLEDGE_DIR",
    "PLUGINS_DIR",
    "PROFILE_BACKUPS_DIR",
    "TITLEIDS_PATH",
    "StoragePaths",
    "app_root",
    "describe_storage",
    "ensure_app_dirs",
    "ensure_user_titleids_file",
    "executable_root",
    "portable_mode_enabled",
    "resolve_storage_paths",
    "resource_path",
]

